[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

[functions]
  node_bundler = "nft"

# Removed function-specific timeout - will use account default (10s for free/pro, 26s for business+)
# The optimizations in analyze.js should keep response time under 15 seconds
